LD_STR = "add {tgt}, x0, {src}"
LI_STR = "li {tgt}, {src}"
ADDI_STR = "addi {tgt}, {src1}, {imm}"
ADD_STR = "add {tgt}, {src1}, {src2}"
NEG_STR = "neg {var}, {var}"


XORI_STR = "xori {tgt}, {src1}, {imm}"
XORI_0_STR = "xori {tgt}, {src1}, 0"

BR_EQUALS_STR = "beq {src1}, {src2}, {label}"
BEZ_STR = "beqz {src}, {label}"

LIST_ADD = "list_add {tgt} {arg1} {arg2}"
CREATE_LIST_STR = "{func} {var} {len} " 
CREATE_DICT_STR = "create_dict {var}"
EQUALS_STR = "{func} {tgt} {arg1} {arg2} "
SET_SUBSCIPT_FUNC_STR = "{func} {tgt} {arg1} {arg2} {arg3}"
GET_SUBSCRIPT_FUNC_STR = "{func} {tgt} {arg1} {arg2}"
PRINT_STR = "print {var}"
EVAL_INPUT_STR = "eval_input {var}"
INT_STR = "{op} {tgt} {left_op} {right_op}"
CREATE_CLOSURE_STR = "create_closure ${func_ptr} {tgt} {free_vars}"
GET_FREE_VARS_STR = "get_free_vars {func_ptr}"
FUNCTION_DEF_STR = "function {func}"
RETURN_STR = "return {var}"
IF_STR = "if{label}:"
THEN_STR = "then{label}:"
ELSE_STR = "else{label}:"
WHILE_STR = "while{label}:"
LOOP_STR = "loop{label}:"
END_IF_STR = "end_if{label}:"
END_WHILE_STR = "end_while{label}:"
WHILE_ELSE_STR = "while_else{label}:"
JE_ELSE_STR = "je else{label}"
JE_END_IF_STR = "je end_if{label}"
JE_END_WHILE_STR = "je end_while{label}"
DATA_TYPE_STR = "{func} {tgt}, {src}"
JMP_END_IF_STR = "j end_if{label}"
JMP_END_WHILE_STR = "j end_while{label}"
JMP_WHILE_STR = "j while{label}"
RETURN_FUNCTION_STR = "function_return {tgt} {args}"